name: quickbite
description: Series2 Ecommerce.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  flutter_staggered_grid_view: ^0.4.0
  provider: ^5.0.0
    
  flutter_rating_bar: ^3.0.1+1
  flutter_svg: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/ 
    - assets/images/
    - assets/images/furniture/
    - assets/images/furniture/items/
 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

